### ISSUE TITLE
BUG: Cli command styleguide:render doesn't work

### ISSUE THREAD

**Issue by jonnitto** [sitegeist/Sitegeist.Monocle#112]
It seems, that the CLI command `styleguide:render` does not work. If I run this command, I'll get the following error:

```bash
Class 'Neos\Flow\Http\Request' not found

  Type: Error
  File: Packages/Plugins/Sitegeist.Monocle/Classes/Service/DummyControllerContextTr
        ait.php
  Line: 24
```

### Versions
Flow: 6.1.0
Neos: 5.1.1
Monocle: 7.0.1

**Comment by mficzel** [comment]
... is fixed in master
