### ISSUE TITLE
BUG: Styleguide can not be reseted

### ISSUE THREAD

**Issue by jonnitto** [sitegeist/Sitegeist.Monocle#113]
In earlier versions, it was possible to reset the `@styleguide` 

Example:

```
prototype(Sitegeist.Stampede:Icon.Preview) {
    @styleguide = null
}
```

In the newest version this doesn't work anymore.

Versions

Flow: 6.1.0
Neos: 5.1.1
Monocle: 7.0.1

**Comment by mficzel** [comment]
This is very likely a behavior change of fusion itself. I see no way to fix this in monocle.

On the other hand we have exclude patterns in the settings to disable some prototypes you do not want in your styleguide.

**Comment by mficzel** [comment]
https://github.com/sitegeist/Sitegeist.Monocle/blob/master/README.md#hide-components
