### ISSUE TITLE
Allow to configure default site package key

### ISSUE THREAD

**Issue by grebaldi** [sitegeist/Sitegeist.Monocle#115]
The way we determine the default site package key for the preview module is the following: https://github.com/sitegeist/Sitegeist.Monocle/blob/4596fd339da9cc107756bd3886edf0ef0951ed38/Classes/Service/PackageKeyTrait.php#L25

While this is a good assumption, we should allow to plainly configure the default site package key on top of that and keep the current solution as a fallback.

**Comment by mficzel** [comment]
Would love to have url patterns for that ... in multisite environments i constantly end up in the wrong site ... however since it is important that Monocle runs without flow we cannot simply look at the domain records ... or at least we have to check wether those exits in a failsafe way.

**Comment by mficzel** [comment]
So the best solution would imho be to 'simply' use domain records when available and stick to the current behavior otherwise.
