### ISSUE TITLE
Preview doesn't resize based on image content

### ISSUE THREAD

**Issue by wanicode** [sitegeist/Sitegeist.Monocle#14]
When i want to display an img-Tag with a src, Monocle sometimes doesn't resize the preview window based on the picture size.

**Comment by mficzel** [comment]
Yes a known problem ... it is not so easy to get the load event of an iframe

**Comment by grebaldi** [comment]
This might solve it: #33

**Comment by mficzel** [comment]
I close this since i cannot reproduce this with actual monocle ui any more
