### ISSUE TITLE
Allow props to be removed from Inspector

### ISSUE THREAD

**Issue by bwaidelich** [sitegeist/Sitegeist.Monocle#162]
The feature to allow for configurable [PropEditors](https://github.com/sitegeist/Sitegeist.Monocle#props--prop-editors) is great, but currently it seems impossible to _remove_ an editor from the inspector.

This is especially obstructive when it comes to _container_ components (like Templates) where the full HTML content is rendered into a huge Textarea.

We suggest to extend the `@styleguide` options by an optional `hidePropsInInspector` array that allows to hide certain props from the inspector:

```
prototype(Some.Package:SomeComponent) < prototype(Neos.Fusion:Component) {
    @styleguide {
        options {
            hidePropsInInspector = ${['content']}
        }

        props {
            content = Neos.Fusion:Join {
                0 = Sitegeist.Monocle:Preview.Prototype {
                    prototypeName = 'Some.Package:SomeOtherComponent'
                }
                1 = Sitegeist.Monocle:Preview.Prototype {
                    prototypeName = 'Some.Package:SomeThirdComponent'
                }
            }
        }
    }
    content = ''

    renderer = ....
}
``

**Comment by KPeschke** [comment]
+1
