### ISSUE TITLE
Wrong height if an element has a display:flex property

### ISSUE THREAD

**Issue by jonnitto** [sitegeist/Sitegeist.Monocle#43]
If I have an element with `display:flex` the height of the `iframe` get's wrong calculated, especially if I have `margin-top` and/or `margin-bottom` on the element

**Comment by mficzel** [comment]
@jonnitto This seems to be solved in 4.0 can you test and close the issue if that is the case.

**Comment by jonnitto** [comment]
Sorry for the late answer. I will test it.
