### ISSUE TITLE
Wrong sitePackageKey on load trough proxy (BrowserSync)

### ISSUE THREAD

**Issue by KPeschke** [sitegeist/Sitegeist.Monocle#73]
Open monocle like this:
https://localhost:3000/monocle/preview/module/Internezzo.Esademo/Internezzo.Renderer:Share

"An error occured
 The prototype list is empty. Please check the Root.fusion file in your site package "odule" and make sure your components are included correctly."
 
In network panel the following url is requested
https://localhost:3000/monocle/api/styleguideobjects?sitePackageKey=odule

Sitegeist.Monocle Version: 4.0.x

**Comment by mficzel** [comment]
@grebaldi I suspect this happens in the react routing. I already checked that the endpoint-urls rendered as data-attributes in the template are valid. Some of those might need an `absolute:true` but still this does not explain `sitePackageKey=odule`.

**Comment by mficzel** [comment]
The reason behind is this browserSync issue: https://github.com/BrowserSync/browser-sync/issues/1147

Basically the requests that are proxied via browserSync have no protocol and thus the default routing does not work

**Comment by KPeschke** [comment]
Many thanks for quickly fixing and the new reales v4.1.0.
