### ISSUE TITLE
Monocle 4.2 is not compatible with Neos 3.3

### ISSUE THREAD

**Issue by breadlesscode** [sitegeist/Sitegeist.Monocle#84]
Please update the composer file. The latest Version of Monocle is not longer compatible with Neos 3.3.

Last but not least, thanks for this awesome Package :)

**Comment by mficzel** [comment]
@breadlesscode please check again with Monocle 4.2.1

**Comment by breadlesscode** [comment]
Thanks for the quick response. Seems to work :+1:
